# Generated by Django 4.1.5 on 2023-06-23 13:35

import PAS_app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dept_title", models.CharField(max_length=30, unique=True)),
                ("dept_desc", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dept_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/department/"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Departments", "db_table": "Department",},
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_title", models.CharField(max_length=30, unique=True)),
                (
                    "programme_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={"verbose_name_plural": "Programmes", "db_table": "Programme",},
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_title", models.CharField(max_length=9, unique=True)),
                (
                    "session_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={"verbose_name_plural": "Sessions", "db_table": "Session",},
        ),
        migrations.CreateModel(
            name="StudentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_title", models.CharField(max_length=30, unique=True)),
                (
                    "type_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Student Types",
                "db_table": "StudentType",
            },
        ),
        migrations.CreateModel(
            name="SupervisorRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_number",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "rank_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Supervisor Rank",
                "db_table": "Supervisor Rank",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_number", models.CharField(max_length=10, unique=True)),
                ("title_description", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Supervisor Title",
                "db_table": "Supervisor Title",
            },
        ),
        migrations.CreateModel(
            name="SupervisorsFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=PAS_app.models.path_and_rename_super),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "prog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Supervisors Files",
                "db_table": "Supervisors File",
            },
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=PAS_app.models.path_and_rename)),
                ("used", models.BooleanField(default=False)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.session",
                    ),
                ),
                (
                    "student_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.studenttype",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Files", "db_table": "File",},
        ),
    ]
