# Generated by Django 4.1.5 on 2023-08-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
