# Generated by Django 4.0.6 on 2022-08-18 13:43

import PAS_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0002_remove_supervisorsfiles_programme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=30, unique=True)),
                ('department_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'Department',
            },
        ),
        migrations.AlterField(
            model_name='supervisorsfiles',
            name='file',
            field=models.FileField(upload_to=PAS_app.models.path_and_rename_super),
        ),
    ]
