# Generated by Django 4.0.6 on 2022-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0003_department_alter_supervisorsfiles_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_description',
            new_name='dept_desc',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_title',
            new_name='dept_title',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/department/'),
        ),
    ]
