# Generated by Django 4.0.6 on 2022-08-19 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0004_rename_department_description_department_dept_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
