# Generated by Django 4.0.6 on 2022-08-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0005_remove_department_id_department_dept_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
