# Generated by Django 4.0.6 on 2022-08-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0010_files_used_supervisorsfiles_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorrank',
            name='rank_title',
        ),
        migrations.AddField(
            model_name='supervisorrank',
            name='rank_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
