# Generated by Django 4.1.1 on 2022-09-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0011_remove_supervisorrank_rank_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorsfiles',
            name='prog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme'),
            preserve_default=False,
        ),
    ]
