# Generated by Django 4.1.1 on 2022-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0012_supervisorsfiles_prog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=10, unique=True)),
                ('title_description', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Supervisor Title',
                'db_table': 'Supervisor Title',
            },
        ),
    ]
