# Generated by Django 4.1.5 on 2023-08-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_payment", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="description",
            field=models.CharField(default="Project Fee", max_length=500),
            preserve_default=False,
        ),
    ]
