# Generated by Django 4.1.5 on 2023-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_payment", "0003_payments_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="payments",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
