# Generated by Django 4.1.5 on 2023-08-26 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_payment", "0004_payments_transaction_id_alter_payments_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="payments", name="id",),
        migrations.AddField(
            model_name="payments",
            name="payment_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
