# Generated by Django 4.1.5 on 2023-08-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_app", "0002_session_is_current"),
        ("PAS_payment", "0005_remove_payments_id_payments_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PAS_app.session",
            ),
        ),
    ]
