# Generated by Django 4.1.5 on 2023-06-23 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("PAS_auth", "0001_initial"),
        ("PAS_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "venue_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("venue_title", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "prog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Venues", "db_table": "Venues",},
        ),
        migrations.CreateModel(
            name="StudHallAllocation",
            fields=[
                (
                    "studHall_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("day_num", models.IntegerField(default=1)),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "prog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
                (
                    "sess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.session",
                    ),
                ),
                (
                    "stud_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_auth.studentprofile",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.studenttype",
                    ),
                ),
                (
                    "venue_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_hallAllocation.venue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Hall Allocations",
                "db_table": "Student Hall Allocation",
            },
        ),
        migrations.CreateModel(
            name="DaysOfDefense",
            fields=[
                (
                    "days_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("num_of_day", models.IntegerField(default=3)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "prog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
                (
                    "sess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.session",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.studenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Days Of Defenses",
                "db_table": "Days Of Defense",
            },
        ),
        migrations.CreateModel(
            name="AssessorHallAllocation",
            fields=[
                (
                    "assessHall_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "assessor_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessor_one",
                        to="PAS_auth.supervisorprofile",
                    ),
                ),
                (
                    "assessor_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessor_two",
                        to="PAS_auth.supervisorprofile",
                    ),
                ),
                (
                    "chief_assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_auth.supervisorprofile",
                    ),
                ),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "prog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
                (
                    "sess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.session",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.studenttype",
                    ),
                ),
                (
                    "venue_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_hallAllocation.venue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Assessors Hall Allocations",
                "db_table": "Assessor Hall Allocation",
            },
        ),
    ]
