# Generated by Django 4.1.2 on 2022-11-30 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PAS_app', '0013_title'),
        ('PAS_auth', '0025_supervisorprofile_super_nd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('venue_title', models.CharField(max_length=100)),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme')),
            ],
            options={
                'verbose_name_plural': 'Venues',
                'db_table': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='StudHallAllocation',
            fields=[
                ('studHall_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day_num', models.IntegerField(default=1)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department')),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.session')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.studentprofile')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_hallAllocation.venue')),
            ],
            options={
                'verbose_name_plural': 'Student Hall Allocations',
                'db_table': 'Student Hall Allocation',
            },
        ),
        migrations.CreateModel(
            name='DaysOfDefense',
            fields=[
                ('days_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('num_of_day', models.IntegerField(default=3)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department')),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme')),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.session')),
            ],
            options={
                'verbose_name_plural': 'Days Of Defenses',
                'db_table': 'Days Of Defense',
            },
        ),
        migrations.CreateModel(
            name='AssessorHallAllocation',
            fields=[
                ('assessHall_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isChief', models.BooleanField(default=False)),
                ('super_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.supervisorprofile')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_hallAllocation.venue')),
            ],
            options={
                'verbose_name_plural': 'Assessors Hall Allocations',
                'db_table': 'Assessor Hall Allocation',
            },
        ),
    ]
