# Generated by Django 4.1.2 on 2022-11-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0013_title'),
        ('PAS_hallAllocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessorhallallocation',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessorhallallocation',
            name='prog_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessorhallallocation',
            name='sess_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PAS_app.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studhallallocation',
            name='prog_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme'),
            preserve_default=False,
        ),
    ]
