# Generated by Django 4.1.2 on 2022-11-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_hallAllocation', '0002_assessorhallallocation_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_title',
            field=models.CharField(max_length=200),
        ),
    ]
