# Generated by Django 4.1.2 on 2022-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_hallAllocation', '0003_alter_venue_venue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
