# Generated by Django 4.1.2 on 2022-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_hallAllocation', '0004_venue_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
