# Generated by Django 4.1.2 on 2022-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_hallAllocation', '0005_alter_venue_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofdefense',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
