# Generated by Django 4.1.2 on 2022-12-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0013_title'),
        ('PAS_hallAllocation', '0006_daysofdefense_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofdefense',
            name='student_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PAS_app.studenttype'),
            preserve_default=False,
        ),
    ]
