# Generated by Django 4.1.2 on 2022-12-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_hallAllocation', '0007_daysofdefense_student_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysofdefense',
            old_name='student_type_id',
            new_name='type_id',
        ),
    ]
