# Generated by Django 4.1.2 on 2022-12-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0013_title'),
        ('PAS_hallAllocation', '0008_rename_student_type_id_daysofdefense_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studhallallocation',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PAS_app.studenttype'),
            preserve_default=False,
        ),
    ]
