# Generated by Django 4.0.6 on 2022-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True),
        ),
    ]
