# Generated by Django 4.0.6 on 2022-08-22 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0010_files_used_supervisorsfiles_used'),
        ('PAS_auth', '0003_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('super_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department')),
                ('rank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.supervisorrank')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supervisor Profile',
                'db_table': 'Supervisor Profile',
            },
        ),
    ]
