# Generated by Django 4.0.6 on 2022-08-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0010_files_used_supervisorsfiles_used'),
        ('PAS_auth', '0005_studentprofile_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.studenttype'),
        ),
    ]
