# Generated by Django 4.0.6 on 2022-08-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0011_remove_supervisorrank_rank_title_and_more'),
        ('PAS_auth', '0006_alter_studentprofile_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asst_coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asst_coord', to='PAS_auth.supervisorprofile')),
                ('chief_coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief_coord', to='PAS_auth.supervisorprofile')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department')),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme')),
            ],
            options={
                'verbose_name_plural': 'Coordinators Details',
                'db_table': 'Coordinator Details',
            },
        ),
    ]
