# Generated by Django 4.0.6 on 2022-08-27 11:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0011_remove_supervisorrank_rank_title_and_more'),
        ('PAS_auth', '0007_coordinators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('allocate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_num', models.CharField(max_length=500)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department')),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme')),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.session')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.studentprofile')),
                ('super_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.supervisorprofile')),
            ],
            options={
                'verbose_name_plural': 'Allocation Details',
                'db_table': 'Allocation Details',
            },
        ),
    ]
