# Generated by Django 4.0.6 on 2022-08-29 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0011_remove_supervisorrank_rank_title_and_more'),
        ('PAS_auth', '0008_allocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocate',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PAS_app.studenttype'),
        ),
    ]
