# Generated by Django 4.0.6 on 2022-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0011_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_num',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='groups',
            table='Groups',
        ),
    ]
