# Generated by Django 4.0.6 on 2022-09-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0012_alter_groups_options_alter_groups_group_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocate',
            name='group_num',
        ),
        migrations.AddField(
            model_name='allocate',
            name='group_id',
            field=models.ForeignKey(default=115, on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.groups'),
            preserve_default=False,
        ),
    ]
