# Generated by Django 4.0.6 on 2022-09-08 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0016_emailsendcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='pic',
            field=models.ImageField(default='img/comlogo.png', null=True, upload_to='uploads/profile/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
