# Generated by Django 4.0.6 on 2022-09-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0017_studentprofile_pic_alter_studentprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='pic',
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, default='img/comlogo.png', null=True, upload_to='uploads/profile/'),
        ),
    ]
