# Generated by Django 4.1.1 on 2022-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0020_remove_user_firstname_remove_user_lastname_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='capacity',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
