# Generated by Django 4.1.1 on 2022-10-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0013_title'),
        ('PAS_auth', '0021_supervisorprofile_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PAS_app.title'),
            preserve_default=False,
        ),
    ]
