# Generated by Django 4.1.1 on 2022-10-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0022_supervisorprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='capacity',
            field=models.CharField(max_length=10),
        ),
    ]
