# Generated by Django 4.1.1 on 2022-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_auth', '0024_remove_supervisorprofile_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='super_nd',
            field=models.BooleanField(default=False),
        ),
    ]
