# Generated by Django 4.1.5 on 2023-06-23 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "assess_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("seminar_defense_grade", models.IntegerField(default=0)),
                ("project_defense_grade", models.IntegerField(default=0)),
                ("supervisor_grade", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "Assessments", "db_table": "Assessment",},
        ),
    ]
