# Generated by Django 4.1.5 on 2023-06-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("PAS_auth", "0001_initial"),
        ("PAS_hallAllocation", "0001_initial"),
        ("PAS_assessment", "0001_initial"),
        ("PAS_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="assessor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="PAS_auth.supervisorprofile",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PAS_app.department"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="prog_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PAS_app.programme"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="sess_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PAS_app.session"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="PAS_hallAllocation.studhallallocation",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PAS_app.studenttype"
            ),
        ),
    ]
