# Generated by Django 4.1.5 on 2023-07-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_auth", "0001_initial"),
        ("PAS_assessment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="assessor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PAS_auth.supervisorprofile",
            ),
        ),
    ]
