# Generated by Django 4.1.2 on 2022-11-30 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_app', '0013_title'),
        ('PAS_auth', '0025_supervisorprofile_super_nd'),
        ('PAS_assessment', '0002_alter_daysofdefense_num_of_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assess_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('seminar_defense_grade', models.IntegerField(default=0)),
                ('project_defense_grade', models.IntegerField(default=0)),
                ('supervisor_grade', models.IntegerField(default=0)),
                ('assessor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.supervisorprofile')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.department')),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.programme')),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_app.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_auth.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Assessments',
                'db_table': 'Assessment',
            },
        ),
        migrations.RemoveField(
            model_name='daysofdefense',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='daysofdefense',
            name='prog_id',
        ),
        migrations.RemoveField(
            model_name='daysofdefense',
            name='sess_id',
        ),
        migrations.RemoveField(
            model_name='studhallallocation',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='studhallallocation',
            name='sess_id',
        ),
        migrations.RemoveField(
            model_name='studhallallocation',
            name='stud_id',
        ),
        migrations.RemoveField(
            model_name='studhallallocation',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='prog_id',
        ),
        migrations.DeleteModel(
            name='AssessorHallAllocation',
        ),
        migrations.DeleteModel(
            name='DaysOfDefense',
        ),
        migrations.DeleteModel(
            name='StudHallAllocation',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
