# Generated by Django 4.1.2 on 2022-12-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_hallAllocation', '0010_rename_super_id_assessorhallallocation_chief_assessor_and_more'),
        ('PAS_assessment', '0003_assessment_remove_daysofdefense_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAS_hallAllocation.studhallallocation'),
        ),
    ]
