# Generated by Django 4.1.5 on 2023-07-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_auth", "0001_initial"),
        ("PAS_assessment", "0003_alter_assessment_assessor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_assessment",
                to="PAS_auth.supervisorprofile",
            ),
        ),
    ]
