# Generated by Django 4.1.5 on 2023-08-01 02:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_auth", "0001_initial"),
        ("PAS_app", "0001_initial"),
        ("PAS_hallAllocation", "0001_initial"),
        ("PAS_assessment", "0004_assessment_supervisor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeminarAssessment",
            fields=[
                (
                    "assess_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "seminar_defense_grade",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(
                                100, message="Grade can't be more than 100"
                            ),
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "assessor_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_auth.supervisorprofile",
                    ),
                ),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "prog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
                (
                    "sess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.session",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_hallAllocation.studhallallocation",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.studenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seminar Assessments",
                "db_table": "Seminar Assessment",
            },
        ),
        migrations.CreateModel(
            name="ProjectAssessment",
            fields=[
                (
                    "assess_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "project_defense_grade",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(
                                50, message="Grade can't be more than 50"
                            ),
                        ],
                    ),
                ),
                (
                    "supervisor_grade",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(
                                50, message="Grade can't be more than 50"
                            ),
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "assessor_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assessor",
                        to="PAS_auth.supervisorprofile",
                    ),
                ),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.department",
                    ),
                ),
                (
                    "prog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.programme",
                    ),
                ),
                (
                    "sess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.session",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_hallAllocation.studhallallocation",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_supervisor",
                        to="PAS_auth.supervisorprofile",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAS_app.studenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Assessments",
                "db_table": "Project Assessment",
            },
        ),
    ]
