# Generated by Django 4.1.2 on 2022-12-26 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PAS_assessment', '0005_assessment_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
