# Generated by Django 4.1.5 on 2023-08-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PAS_auth", "0001_initial"),
        (
            "PAS_assessment",
            "0006_rename_assessor_id_projectassessment_assessor_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectassessment", old_name="assessor", new_name="assessor_id",
        ),
        migrations.RenameField(
            model_name="projectassessment", old_name="student", new_name="student_id",
        ),
        migrations.RenameField(
            model_name="seminarassessment", old_name="student", new_name="student_id",
        ),
        migrations.RemoveField(model_name="seminarassessment", name="assessor",),
        migrations.AddField(
            model_name="seminarassessment",
            name="assessor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PAS_auth.supervisorprofile",
            ),
        ),
    ]
